//------------------------------------------------------------------------------------
// build.rs -- Part of RHoiScribe
//
// Copyright (C) 2026 CzXieDdan. All rights reserved.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// https://github.com/czxieddan/RHoiScribe
//------------------------------------------------------------------------------------

use std::{
    env,
    ffi::OsStr,
    fs,
    io::{self, Cursor, ErrorKind, Read},
    path::{Path, PathBuf},
    process::Command,
};

use sha2::{Digest, Sha256};

#[allow(dead_code)]
#[path = "src/cwt/hoi4_config.rs"]
mod hoi4_config;

use hoi4_config::HOI4_CWT_CONFIG;

fn main() -> io::Result<()> {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=resources/RHoiScribe.ico");

    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("out dir"));
    generate_knowledge_manifest(&manifest_dir, &out_dir)?;
    generate_cwt_config_archive(&out_dir)?;

    if env::var("CARGO_CFG_WINDOWS").is_err() {
        return Ok(());
    }

    let icon_path = manifest_dir.join("resources").join("RHoiScribe.ico");
    let rc_path = out_dir.join("rhoiscribe.rc");
    let res_path = out_dir.join("rhoiscribe.res");

    fs::write(&rc_path, windows_resource_script(&icon_path))?;

    compile_resource(&rc_path, &res_path)?;

    println!("cargo:rustc-link-arg-bin=rhoiscribe={}", res_path.display());

    Ok(())
}

struct CwtArchiveSummary {
    source_count: usize,
    total_bytes: usize,
    content_sha256: String,
}

fn generate_cwt_config_archive(out_dir: &Path) -> io::Result<()> {
    for env_name in [
        "HTTPS_PROXY",
        "https_proxy",
        "HTTP_PROXY",
        "http_proxy",
        "ALL_PROXY",
        "all_proxy",
    ] {
        println!("cargo:rerun-if-env-changed={env_name}");
    }

    let archive_path = out_dir.join("hoi4_cwt_config.zip");
    fetch_hoi4_cwt_archive(out_dir, &archive_path)?;
    let archive_bytes = fs::read(&archive_path)?;
    let summary = inspect_hoi4_cwt_archive(&archive_bytes)?;

    let generated = format!(
        "// This file is generated by build.rs.\n\
         pub(crate) const HOI4_CWT_CONFIG_CONTENT_SHA256: &str = {};\n\
         pub(crate) const HOI4_CWT_CONFIG_SOURCE_COUNT: usize = {};\n\
         pub(crate) const HOI4_CWT_CONFIG_TOTAL_BYTES: usize = {};\n\
         pub(crate) const HOI4_CWT_CONFIG_ARCHIVE_BYTES: &[u8] = include_bytes!({});\n",
        rust_string_literal(&summary.content_sha256),
        summary.source_count,
        summary.total_bytes,
        rust_string_literal(&archive_path.to_string_lossy()),
    );
    fs::write(out_dir.join("hoi4_cwt_config.rs"), generated)
}

fn fetch_hoi4_cwt_archive(out_dir: &Path, archive_path: &Path) -> io::Result<()> {
    let git_dir = out_dir.join("hoi4_cwt_config_git");
    fs::create_dir_all(&git_dir)?;

    run_git_command(out_dir, ["init".to_string(), path_to_string(&git_dir)])?;
    ensure_git_remote(&git_dir)?;
    run_git_command(
        &git_dir,
        [
            "fetch".to_string(),
            "--depth=1".to_string(),
            "origin".to_string(),
            HOI4_CWT_CONFIG.revision.to_string(),
        ],
    )?;
    run_git_command(
        &git_dir,
        [
            "cat-file".to_string(),
            "-e".to_string(),
            format!("{}^{{commit}}", HOI4_CWT_CONFIG.revision),
        ],
    )?;
    run_git_command(
        &git_dir,
        [
            "archive".to_string(),
            "--format=zip".to_string(),
            "--output".to_string(),
            path_to_string(archive_path),
            HOI4_CWT_CONFIG.revision.to_string(),
            HOI4_CWT_CONFIG.source_directory.to_string(),
        ],
    )
}

fn ensure_git_remote(git_dir: &Path) -> io::Result<()> {
    let remote_result = git_command(
        git_dir,
        [
            "remote".to_string(),
            "get-url".to_string(),
            "origin".to_string(),
        ],
    )
    .output();

    match remote_result {
        Ok(output) if output.status.success() => run_git_command(
            git_dir,
            [
                "remote".to_string(),
                "set-url".to_string(),
                "origin".to_string(),
                HOI4_CWT_CONFIG.git_url(),
            ],
        ),
        _ => run_git_command(
            git_dir,
            [
                "remote".to_string(),
                "add".to_string(),
                "origin".to_string(),
                HOI4_CWT_CONFIG.git_url(),
            ],
        ),
    }
}

fn run_git_command<I>(cwd: &Path, args: I) -> io::Result<()>
where
    I: IntoIterator<Item = String>,
{
    let args = args.into_iter().collect::<Vec<_>>();
    let output = git_command(cwd, args.clone()).output().map_err(|error| {
        io::Error::new(
            error.kind(),
            format!("failed to run git {}: {}", args.join(" "), error),
        )
    })?;

    if output.status.success() {
        return Ok(());
    }

    Err(io::Error::other(format!(
        "git {} failed with {}\nstdout:\n{}\nstderr:\n{}",
        args.join(" "),
        output.status,
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    )))
}

fn git_command<I>(cwd: &Path, args: I) -> Command
where
    I: IntoIterator<Item = String>,
{
    let mut command = Command::new("git");
    command.current_dir(cwd);

    if cfg!(windows) {
        command
            .arg("-c")
            .arg("http.sslBackend=schannel")
            .arg("-c")
            .arg("http.schannelCheckRevoke=false");
    }

    if let Some(proxy_url) = proxy_url_from_env() {
        command
            .arg("-c")
            .arg(format!("http.proxy={proxy_url}"))
            .arg("-c")
            .arg(format!("https.proxy={proxy_url}"));
    }

    command.args(args);
    command
}

fn proxy_url_from_env() -> Option<String> {
    [
        "HTTPS_PROXY",
        "https_proxy",
        "HTTP_PROXY",
        "http_proxy",
        "ALL_PROXY",
        "all_proxy",
    ]
    .into_iter()
    .find_map(|name| env::var(name).ok().filter(|value| !value.trim().is_empty()))
}

fn inspect_hoi4_cwt_archive(archive_bytes: &[u8]) -> io::Result<CwtArchiveSummary> {
    let cursor = Cursor::new(archive_bytes);
    let mut archive = zip::ZipArchive::new(cursor).map_err(|error| {
        io::Error::new(
            ErrorKind::InvalidData,
            format!("failed to read CWT config archive: {error}"),
        )
    })?;
    let mut sources = Vec::new();

    for index in 0..archive.len() {
        let mut file = archive.by_index(index).map_err(|error| {
            io::Error::new(
                ErrorKind::InvalidData,
                format!("failed to read CWT config archive entry: {error}"),
            )
        })?;
        if !file.is_file() {
            continue;
        }

        let entry_name = file.name().replace('\\', "/");
        let Some(relative_path) = HOI4_CWT_CONFIG.archive_source_relative_path(&entry_name) else {
            continue;
        };
        if !relative_path.ends_with(".cwt") {
            continue;
        }

        let mut content = Vec::new();
        file.read_to_end(&mut content).map_err(|error| {
            io::Error::new(
                ErrorKind::InvalidData,
                format!("failed to read CWT config entry `{entry_name}`: {error}"),
            )
        })?;
        sources.push((relative_path.to_string(), content));
    }

    sources.sort_by(|left, right| left.0.cmp(&right.0));
    if sources.is_empty() {
        return Err(io::Error::new(
            ErrorKind::InvalidData,
            format!(
                "CWT config archive contains no {}/*.cwt sources",
                HOI4_CWT_CONFIG.source_directory
            ),
        ));
    }

    let total_bytes = sources.iter().map(|(_, content)| content.len()).sum();
    Ok(CwtArchiveSummary {
        source_count: sources.len(),
        total_bytes,
        content_sha256: content_sha256(&sources),
    })
}

fn content_sha256(sources: &[(String, Vec<u8>)]) -> String {
    let mut hasher = Sha256::new();
    for (path, content) in sources {
        hasher.update(path.as_bytes());
        hasher.update([0]);
        hasher.update(content);
        hasher.update([0]);
    }
    format!("{:x}", hasher.finalize())
}

fn generate_knowledge_manifest(manifest_dir: &Path, out_dir: &Path) -> io::Result<()> {
    let knowledge_root = manifest_dir
        .join("resources")
        .join("knowledge")
        .join("hoi4");
    println!("cargo:rerun-if-changed={}", knowledge_root.display());

    let mut files = Vec::new();
    collect_toml_files(&knowledge_root, &mut files)?;
    files.sort();

    let mut output = String::from(
        "// This file is generated by build.rs.\n\
         pub(crate) struct EmbeddedKnowledgeSource {\n\
         \x20   pub(crate) path: &'static str,\n\
         \x20   pub(crate) content: &'static str,\n\
         }\n\n\
         pub(crate) const EMBEDDED_KNOWLEDGE_SOURCES: &[EmbeddedKnowledgeSource] = &[\n",
    );

    for file in files {
        println!("cargo:rerun-if-changed={}", file.display());
        let relative_path = file
            .strip_prefix(&knowledge_root)
            .map_err(|error| io::Error::new(ErrorKind::InvalidInput, error.to_string()))?;
        let source_path = clean_manifest_path(relative_path);
        let file_path = file.to_string_lossy();

        output.push_str("    EmbeddedKnowledgeSource { path: ");
        output.push_str(&rust_string_literal(&source_path));
        output.push_str(", content: include_str!(");
        output.push_str(&rust_string_literal(&file_path));
        output.push_str(") },\n");
    }

    output.push_str("];\n");
    fs::write(out_dir.join("knowledge_sources.rs"), output)
}

fn collect_toml_files(root: &Path, files: &mut Vec<PathBuf>) -> io::Result<()> {
    if !root.exists() {
        return Ok(());
    }

    for entry in fs::read_dir(root)? {
        let path = entry?.path();
        if path.is_dir() {
            collect_toml_files(&path, files)?;
        } else if is_toml_file(&path) {
            files.push(path);
        }
    }

    Ok(())
}

fn is_toml_file(path: &Path) -> bool {
    path.extension()
        .and_then(OsStr::to_str)
        .is_some_and(|extension| extension.eq_ignore_ascii_case("toml"))
}

fn clean_manifest_path(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

fn path_to_string(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

fn compile_resource(rc_path: &Path, res_path: &Path) -> io::Result<()> {
    let mut attempted = Vec::new();

    for rc in resource_compilers() {
        let output = match Command::new(&rc)
            .arg("/nologo")
            .arg("/C")
            .arg("65001")
            .arg("/fo")
            .arg(res_path)
            .arg(rc_path)
            .output()
        {
            Ok(output) => output,
            Err(error) if error.kind() == ErrorKind::NotFound => {
                attempted.push(format!("{}: not found", rc.display()));
                continue;
            }
            Err(error) => return Err(error),
        };

        if output.status.success() {
            return Ok(());
        }

        attempted.push(format!(
            "{}: stdout:\n{}\nstderr:\n{}",
            rc.display(),
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        ));
    }

    panic!(
        "failed to compile Windows resources; install llvm-rc or Windows SDK rc.exe, or set RC\n{}",
        attempted.join("\n")
    );
}

fn resource_compilers() -> Vec<PathBuf> {
    if let Some(rc) = env::var_os("RC") {
        vec![PathBuf::from(rc)]
    } else {
        vec![PathBuf::from("llvm-rc"), PathBuf::from("rc")]
    }
}

fn windows_resource_script(icon_path: &Path) -> String {
    let version = env!("CARGO_PKG_VERSION");
    let version_tuple = version_tuple(version);
    let version_string = format!("{}.0", version);
    let icon = rc_string(&icon_path.display().to_string());

    format!(
        r#"1 ICON "{icon}"

1 VERSIONINFO
FILEVERSION {major},{minor},{patch},0
PRODUCTVERSION {major},{minor},{patch},0
FILEFLAGSMASK 0x3fL
FILEFLAGS 0x0L
FILEOS 0x40004L
FILETYPE 0x1L
FILESUBTYPE 0x0L
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904B0"
        BEGIN
            VALUE "CompanyName", "CzXieDdan\0"
            VALUE "FileDescription", "RHoiScribe MCP Server\0"
            VALUE "FileVersion", "{version_string}\0"
            VALUE "InternalName", "rhoiscribe\0"
            VALUE "LegalCopyright", "Copyright © 2026 CzXieDdan\0"
            VALUE "OriginalFilename", "rhoiscribe.exe\0"
            VALUE "ProductName", "RHoiScribe\0"
            VALUE "ProductVersion", "{version_string}\0"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x0409, 1200
    END
END
"#,
        icon = icon,
        major = version_tuple.0,
        minor = version_tuple.1,
        patch = version_tuple.2,
        version_string = version_string,
    )
}

fn version_tuple(version: &str) -> (u16, u16, u16) {
    let mut parts = version.split('.').map(|part| part.parse().unwrap_or(0));
    (
        parts.next().unwrap_or(0),
        parts.next().unwrap_or(0),
        parts.next().unwrap_or(0),
    )
}

fn rc_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn rust_string_literal(value: &str) -> String {
    let mut output = String::from("\"");
    for character in value.chars() {
        match character {
            '\\' => output.push_str("\\\\"),
            '"' => output.push_str("\\\""),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            character if character.is_control() => {
                output.push_str(&format!("\\u{{{:x}}}", character as u32));
            }
            character => output.push(character),
        }
    }
    output.push('"');
    output
}
